version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: earthenoven_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: earthenoven
      POSTGRES_PASSWORD: finedining123
      POSTGRES_DB: earthenoven_reservations
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: earthenoven_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@earthenoven.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres

volumes:
  postgres_data:
